#!/usr/bin/env bash

## Autorun ---------------------------------------------------#

killall -q polybar
polybar bspwm &

## External Monitor 
my_laptop_external_monitor=$(xrandr --query | grep 'HDMI-1')
if [[ $my_laptop_external_monitor = *connected* ]]; then
   polybar external &
fi

## General ---------------------------------------------------#

## Bspwm config directory
BSPDIR="$HOME/.config/bspwm"

## Sxhkd config directory
SXHDIR="$HOME/.config/sxhkd"

## Export bspwm/bin dir to PATH
export PATH="${PATH}:$HOME/.config/bspwm/bin"

## Run java applications without issues
export _JAVA_AWT_WM_NONREPARENTING=1

## Current theme ---------------------------------------------#

## Get the wallpaper
feh --bg-fill --randomize ~/Pictures/walls/

