#!/usr/bin/env bash

## Autostart -------------------------------------------------#

$HOME/.config/bspwm/autostart.sh

## Current theme ---------------------------------------------#

## Get the colors from theme file
FOREGROUND="$foreground"
BACKGROUND="$background"
CURSOR="$cursor"
MYBLACK="#101010"
RED="$color1"
GREEN="$color2"
YELLOW="$color3"
BLUE="$color4"
MAGENTA="$color5"
CYAN="$color6"
WHITE="$color7"
ALTBLACK="$color8"
ALTRED="$color9"
ALTGREEN="$color10"
ALTYELLOW="$color11"
ALTBLUE="$color12"
ALTMAGENTA="$color13"
ALTCYAN="$color14"
ALTWHITE="$color15"

## Bspwm appearance
CURRENT_BORDER='1'
CURRENT_GAP='0'
CURRENT_SRATIO="0.6"

## Configurations --------------------------------------------#

## Manager Workspaces

if [[ $(xrandr --query | grep 'HDMI-1 connected') ]]; then
   bspc monitor \^1 -d 'I' 'II' 'III' 'IV'
   bspc monitor \^2 -d 'V' 'VI' 'VII' 'VIII'
   elif [[ $(xrandr --query | grep 'primary') ]]; then
   bspc monitor \^1 -d 'I' 'II' 'III' 'IV' 'V' 'VI' 'VII' 'VIII'
fi

## Apply bspwm configurations
bspc config border_width "$CURRENT_BORDER"
bspc config window_gap "$CURRENT_GAP"
bspc config split_ratio "$CURRENT_SRATIO"

bspc config focused_border_color "$MYBLACK" 
bspc config normal_border_color "$BACKGROUND"
bspc config active_border_color "$MAGENTA"
bspc config presel_feedback_color "$GREEN"

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle true
bspc config focus_follows_pointer true

## Manage all the unmanaged windows remaining from a previous session.
bspc wm --adopt-orphans

## Window rules ----------------------------------------------#

# remove all rules first
bspc rule -r *:*

## 1 > terminal (always open terminal on workspace-1)
bspc rule -a Alacritty desktop='^1' follow=on focus=on
# bspc rule -a kitty desktop='^1' follow=on focus=on

## 2 > web (always open web browser on workspace-2)
declare -a web=(Brave-browser Google-chrome Microsoft-edge-dev)
for i in ${web[@]}; do
   bspc rule -a $i desktop='^2' follow=on focus=on; done

## 3 > files (always open file manager on workspace-3)
declare -a files=(Thunar ranger qBittorrent)
for i in ${files[@]}; do
   bspc rule -a $i desktop='^3' follow=on focus=on; done

## 4 > code (always open editors on workspace-4)
declare -a code=(Geany Emacs code-oss Code)
for i in ${code[@]}; do
   bspc rule -a $i desktop='^4' follow=on focus=on state=tiled; done

## 5 > office and docs (always open office/doc apps on workspace-5)
declare -a office=(Gucharmap Atril Evince \
libreoffice-writer libreoffice-calc libreoffice-impress \
libreoffice-startcenter libreoffice Soffice *:libreofficedev *:soffice)
for i in ${office[@]}; do
   bspc rule -a $i desktop='^5' follow=on focus=on; done

## 6 > communication (always open communication apps on workspace-6)
declare -a comm=(TelegramDesktop Hexchat)
for i in ${comm[@]}; do
   bspc rule -a $i desktop='^6' follow=on focus=on; done

## 7 > media (always open media apps on workspace-7)
declare -a media=(Gimp-2.10 obs)
for i in ${media[@]}; do
   bspc rule -a $i desktop='^7' state=floating follow=on focus=on; done

bspc rule -a Spotify desktop='^7' state=floating follow=on focus=on

## 8 > system (always open system apps on workspace-8)
bspc rule -a 'VirtualBox Manager' desktop='^8' follow=on focus=on
bspc rule -a GParted desktop='^8' follow=on focus=on
declare -a settings=(Lxappearance Lxtask Lxrandr Arandr \
System-config-printer.py Pavucontrol Exo-helper-1 \
Xfce4-power-manager-settings)
for i in ${settings[@]}; do
   bspc rule -a $i desktop='^8' state=floating follow=on focus=on; done

## Always Floating Apps
declare -a floating=(alacritty-float Onboard Yad \
Viewnior feh Nm-connection-editor)
for i in ${floating[@]}; do
   bspc rule -a $i state=floating follow=on focus=on; done
